### ISSUE TITLE
Use webview interface module in nativescript-angular project

### ISSUE THREAD

**Issue by raosrinivas1983** [shripalsoni04/nativescript-webview-interface-demo#2]
Can you please provide sample example how to use this module in nativescript-angular2 project setup ?

--Srini

**Comment by shripalsoni04** [comment]
I have created a sample app to show how to use this plugin with angular. Check this sample app at: https://github.com/shripalsoni04/ns-ng-webview-interface-demo

Hope this will be helpful to you.
